services:
  app:
    image: infinite-canvas:prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinite-canvas
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "13000:3000"
    restart: unless-stopped
    networks:
      - baota_net

networks:
  baota_net:
    external: true
